---
- name: Ensure bastion hostname is set correctly
  hosts: localhost
  become: yes
  gather_facts: true
  vars:
    expected_hostname: "bastion.kube.lan"

  tasks:
    - name: Check current static hostname
      command: hostnamectl --static
      changed_when: false
      check_mode: no
      register: current_hostname_result

    - name: Set hostname to {{ expected_hostname }}
      hostname:
        name: "{{ expected_hostname }}"
      register: hostname_change
      when: current_hostname_result.stdout.strip() != expected_hostname

    - name: Confirm hostname update
      ansible.builtin.debug:
        msg: "[OK] Hostname successfully set to {{ expected_hostname }}"
      when: hostname_change is changed

    - name: Confirm hostname already correct
      ansible.builtin.debug:
        msg: "[OK] Hostname is already {{ expected_hostname }} — no change needed"
      when: current_hostname_result.stdout.strip() == expected_hostname
