---
- name: Generate SSH key on bastion and deploy to target nodes
  hosts: localhost
  become: true
  vars:
    ssh_key_path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    target_hosts:
      - "10.0.0.11"
      - "10.0.0.12"
      - "10.0.0.211"
      - "10.0.0.212"
      - "10.0.0.213"
      - "10.0.0.221"
      - "10.0.0.222"
    root_password: "123"

  tasks:
    - name: Ensure sshpass is installed (required for password-based SSH)
      apt:
        name: sshpass
        state: present
        update_cache: yes

    - name: Ensure ~/.ssh directory exists
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: '0700'
      become: false

    - name: Generate ed25519 SSH key pair (no passphrase)
      openssh_keypair:
        path: "{{ ssh_key_path }}"
        type: ed25519
        comment: "{{ ansible_user_id }}@{{ ansible_hostname }}"
        regenerate: never
      become: false
      register: keygen

    - name: Read public key content
      slurp:
        src: "{{ ssh_key_path }}.pub"
      become: false
      register: pub_key_slurp

    - name: Set public key as fact
      set_fact:
        pub_key_content: "{{ pub_key_slurp.content | b64decode | trim }}"

    - name: Deploy SSH key to each target host
      delegate_to: "{{ item }}"
      vars:
        ansible_user: root
        ansible_password: "{{ root_password }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ConnectTimeout=8"
      authorized_key:
        user: root
        key: "{{ pub_key_content }}"
        state: present
        manage_dir: true
      register: deploy_result
      failed_when: false  # Do NOT fail the play on unreachable host
      loop: "{{ target_hosts }}"
      loop_control:
        label: "{{ item }}"

    - name: Show deployment summary
      debug:
        msg: |
          {% for host in target_hosts %}
          [{{ host }}] {{
            (hostvars[host].deploy_result is undefined) or
            (hostvars[host].deploy_result.unreachable | default(false)) or
            (hostvars[host].deploy_result.failed | default(false))
            ? 'OFFLINE / UNREACHABLE'
            : (hostvars[host].deploy_result.changed | default(false) ? 'SSH key INSTALLED' : 'SSH key ALREADY PRESENT')
          }}
          {% endfor %}
