---
- name: Install and configure Keepalived
  hosts: localhost
  become: true

  vars:
    keepalived_src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/keepalived/keepalived.conf
    keepalived_dst: /etc/keepalived/keepalived.conf

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install keepalived
      apt:
        name: keepalived
        state: present

    - name: Enable ip_nonlocal_bind (required for VIP)
      sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: "1"
        state: present
        reload: yes

    - name: Ensure keepalived config directory exists
      file:
        path: /etc/keepalived
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy keepalived.conf from repo
      copy:
        src: "{{ keepalived_src }}"
        dest: "{{ keepalived_dst }}"
        owner: root
        group: root
        mode: "0644"
      notify: Restart keepalived

    - name: Enable and start keepalived service
      systemd:
        name: keepalived
        enabled: yes
        state: started

  handlers:
    - name: Restart keepalived
      systemd:
        name: keepalived
        state: restarted
