---
- name: Full Ubuntu system setup with services
  hosts: localhost
  become: true

  tasks:

    # -------- SSH --------
    - name: Allow root login via password and key
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        backrefs: yes
      loop:
        - { regexp: '^#?PermitRootLogin\s+.*', line: 'PermitRootLogin yes' }
        - { regexp: '^#?PasswordAuthentication\s+.*', line: 'PasswordAuthentication yes' }
        - { regexp: '^#?UsePAM\s+.*', line: 'UsePAM yes' }

    - name: Set root password
      ansible.builtin.user:
        name: root
        password: "{{ '123' | password_hash('sha512') }}"

    - name: Restart SSH service
      ansible.builtin.service:
        name: ssh
        state: restarted
        enabled: true

    # -------- SSH KEYGEN --------
    - name: Ensure /root/.ssh directory exists
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Generate ed25519 SSH key for root (no passphrase)
      ansible.builtin.command: >
        ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ""
      args:
        creates: /root/.ssh/id_ed25519

    - name: Set permissions on private key
      ansible.builtin.file:
        path: /root/.ssh/id_ed25519
        owner: root
        group: root
        mode: "0600"

    - name: Set permissions on public key
      ansible.builtin.file:
        path: /root/.ssh/id_ed25519.pub
        owner: root
        group: root
        mode: "0644"

    # -------- Swap --------
    - name: Disable swap in fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '(\s+swap\s+)'
        replace: '#\1'

    - name: Turn off swap immediately
      ansible.builtin.command: swapoff -a
      ignore_errors: yes

    # -------- UFW --------
    - name: Disable UFW
      ansible.builtin.service:
        name: ufw
        state: stopped
        enabled: false
      ignore_errors: yes

    # -------- Keepalived --------
    - name: Install Keepalived
      ansible.builtin.apt:
        name: keepalived
        state: present
        update_cache: yes

    - name: Enable ip_nonlocal_bind
      ansible.builtin.sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: "1"
        state: present
        reload: yes

    - name: Ensure keepalived config directory exists
      ansible.builtin.file:
        path: /etc/keepalived
        state: directory
        mode: "0755"

    - name: Copy keepalived.conf
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/keepalived/keepalived.conf
        dest: /etc/keepalived/keepalived.conf
        mode: "0644"

    - name: Enable and start keepalived
      ansible.builtin.systemd:
        name: keepalived
        enabled: yes
        state: started

    # -------- BIND --------
    - name: Install BIND9
      ansible.builtin.apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Ensure BIND zones directory exists
      ansible.builtin.file:
        path: /etc/bind/zones
        state: directory
        mode: 0755

    - name: Copy named.conf.options
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/dns/named.conf.options
        dest: /etc/bind/named.conf.options
        backup: yes

    - name: Copy named.conf.local
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/dns/named.conf.local
        dest: /etc/bind/named.conf.local
        backup: yes

    - name: Copy forward zone
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/dns/zones/db.kube.lan
        dest: /etc/bind/zones/db.kube.lan
        backup: yes

    - name: Copy reverse zone
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/dns/zones/db.reverse
        dest: /etc/bind/zones/db.reverse
        backup: yes

    - name: Restart BIND9
      ansible.builtin.service:
        name: bind9
        state: restarted
        enabled: true
