---
- name: Full Ubuntu system setup with services
  hosts: localhost
  become: true

  tasks:

    # -------- SSH (smart & idempotent) --------

    - name: Read sshd_config
      ansible.builtin.slurp:
        path: /etc/ssh/sshd_config
      register: sshd_config_raw
      changed_when: false

    - name: Decode sshd_config
      ansible.builtin.set_fact:
        sshd_config: "{{ sshd_config_raw.content | b64decode }}"
      changed_when: false

    # ---- PermitRootLogin ----
    - name: Ensure PermitRootLogin yes
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#\s]*PermitRootLogin\s+'
        line: 'PermitRootLogin yes'
      when: "'PermitRootLogin yes' not in sshd_config"
      notify: Restart SSH

    # ---- PasswordAuthentication ----
    - name: Ensure PasswordAuthentication yes
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#\s]*PasswordAuthentication\s+'
        line: 'PasswordAuthentication yes'
      when: "'PasswordAuthentication yes' not in sshd_config"
      notify: Restart SSH

    # ---- UsePAM ----
    - name: Ensure UsePAM yes
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#\s]*UsePAM\s+'
        line: 'UsePAM yes'
      when: "'UsePAM yes' not in sshd_config"
      notify: Restart SSH

    # ---- Root password (only if different) ----
    - name: Check current root password hash
      ansible.builtin.command: getent shadow root
      register: root_shadow
      changed_when: false

    - name: Set root password if different
      ansible.builtin.user:
        name: root
        password: "{{ '123' | password_hash('sha512') }}"
      when: "'{{ '123' | password_hash('sha512') }}' not in root_shadow.stdout"

  handlers:

    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
        enabled: true

    # -------- SSH KEYGEN (smart & idempotent) --------

    - name: Check if root SSH private key exists
      ansible.builtin.stat:
        path: /root/.ssh/id_ed25519
      register: root_ssh_key

    - name: Ensure /root/.ssh directory exists
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Generate ed25519 SSH key for root (no passphrase)
      ansible.builtin.command: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ""
      when: not root_ssh_key.stat.exists

    - name: Ensure private key permissions are correct
      ansible.builtin.file:
        path: /root/.ssh/id_ed25519
        owner: root
        group: root
        mode: "0600"
      when: root_ssh_key.stat.exists

    - name: Ensure public key permissions are correct
      ansible.builtin.file:
        path: /root/.ssh/id_ed25519.pub
        owner: root
        group: root
        mode: "0644"
      when: root_ssh_key.stat.exists

    # -------- SWAP (smart & idempotent) --------
        # 1. Check if swap is enabled at runtime
    - name: Check runtime swap status
      ansible.builtin.command: swapon --noheadings
      register: swap_runtime
      changed_when: false
      failed_when: false

    # 2. Disable swap ONLY if enabled
    - name: Disable swap if enabled
      ansible.builtin.command: swapoff -a
      when: swap_runtime.stdout | trim != ""

    # 3. Detect ACTIVE (not commented) swap entry in fstab
    - name: Detect active swap entry in fstab
      ansible.builtin.shell: |
        awk '!/^[[:space:]]*#/ && $1 == "/swap.img" { print }' /etc/fstab
      register: swap_fstab_active
      changed_when: false

    # 4. Comment swap entry ONLY if active
    - name: Comment swap entry in fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^[[:space:]]*/swap\.img.*$'
        line: '#/swap.img       none    swap    sw      0       0'
      when: swap_fstab_active.stdout | trim != ""

    # 5. Final verification (read-only)
    - name: Final swap verification
      ansible.builtin.command: swapon --show
      changed_when: false

    # -------- UFW (smart & idempotent) --------

    - name: Check if UFW service exists
      ansible.builtin.stat:
        path: /lib/systemd/system/ufw.service
      register: ufw_service

    - name: Stop and disable UFW if present
      ansible.builtin.service:
        name: ufw
        state: stopped
        enabled: false
      when: ufw_service.stat.exists


# -------- Keepalived (smart & idempotent) --------

- name: Check if Keepalived is installed
  ansible.builtin.apt:
    name: keepalived
    state: present
    update_cache: yes

- name: Ensure ip_nonlocal_bind sysctl is set
  ansible.builtin.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    state: present
    reload: yes

- name: Ensure keepalived config directory exists
  ansible.builtin.file:
    path: /etc/keepalived
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy keepalived.conf only if changed
  ansible.builtin.copy:
    src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/keepalived/keepalived.conf
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
    force: yes

- name: Enable and start keepalived service
  ansible.builtin.systemd:
    name: keepalived
    enabled: yes
    state: started


    # -------- BIND --------
    - name: Install BIND9
      ansible.builtin.apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Ensure BIND zones directory exists
      ansible.builtin.file:
        path: /etc/bind/zones
        state: directory
        mode: 0755

    - name: Copy named.conf.options
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/dns/named.conf.options
        dest: /etc/bind/named.conf.options
        backup: yes

    - name: Copy named.conf.local
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/dns/named.conf.local
        dest: /etc/bind/named.conf.local
        backup: yes

    - name: Copy forward zone
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/dns/zones/db.kube.lan
        dest: /etc/bind/zones/db.kube.lan
        backup: yes

    - name: Copy reverse zone
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/dns/zones/db.reverse
        dest: /etc/bind/zones/db.reverse
        backup: yes

    - name: Restart BIND9
      ansible.builtin.service:
        name: bind9
        state: restarted
        enabled: true

    # -------- DHCP --------
    - name: Install DHCP server
      ansible.builtin.apt:
        name: isc-dhcp-server
        state: present
        update_cache: yes

    - name: Configure DHCP interface
      ansible.builtin.lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: '^INTERFACESv4='
        line: 'INTERFACESv4="ens34"'

    - name: Copy dhcpd.conf
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/dhcp/dhcpd.conf
        dest: /etc/dhcp/dhcpd.conf
        backup: yes

    - name: Restart DHCP server
      ansible.builtin.service:
        name: isc-dhcp-server
        state: restarted
        enabled: true

    # -------- IP Forwarding & NAT --------
    - name: Enable IP forwarding
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

    - name: NAT POSTROUTING rule
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        source: 10.0.0.0/24
        out_interface: ens32
        jump: MASQUERADE

    - name: FORWARD rule LAN to WAN
      ansible.builtin.iptables:
        chain: FORWARD
        in_interface: ens34
        out_interface: ens32
        jump: ACCEPT

    - name: FORWARD established connections
      ansible.builtin.iptables:
        chain: FORWARD
        in_interface: ens32
        out_interface: ens34
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT

    - name: Install iptables-persistent
      ansible.builtin.apt:
        name: iptables-persistent
        state: present
        update_cache: yes

    - name: Save iptables rules
      ansible.builtin.command: netfilter-persistent save
      ignore_errors: yes

    # -------- HAProxy --------
    - name: Install HAProxy
      ansible.builtin.apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Copy haproxy.cfg
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/haproxy/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        backup: yes

    - name: Restart HAProxy
      ansible.builtin.service:
        name: haproxy
        state: restarted
        enabled: true

    # -------- NFS --------
    - name: Install NFS server
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
        update_cache: yes

    - name: Create NFS directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0777"
        owner: 1000
        group: 1000
      loop:
        - /shares/kubernetes/StorageClass/Delete
        - /shares/kubernetes/StorageClass/Retain

    - name: Configure exports
      ansible.builtin.copy:
        dest: /etc/exports
        content: |
          /shares/kubernetes/StorageClass/Delete 10.0.0.0/24(rw,sync,all_squash,anonuid=1000,anongid=1000,no_subtree_check)
          /shares/kubernetes/StorageClass/Retain 10.0.0.0/24(rw,sync,all_squash,anonuid=1000,anongid=1000,no_subtree_check)

    - name: Export NFS shares
      ansible.builtin.command: exportfs -ra

    - name: Restart NFS server
      ansible.builtin.service:
        name: nfs-kernel-server
        state: restarted
        enabled: true

    # -------- Chrony & Timezone --------
    - name: Set timezone
      ansible.builtin.command: timedatectl set-timezone Asia/Kolkata

    - name: Install chrony
      ansible.builtin.apt:
        name: chrony
        state: present
        update_cache: yes

    - name: Copy chrony.conf
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/chrony/chrony.conf
        dest: /etc/chrony/chrony.conf
        backup: yes

    - name: Restart chrony
      ansible.builtin.service:
        name: chrony
        state: restarted
        enabled: true
