---
- name: Ensure DRBD NFS mount point and exports file
  hosts: localhost
  become: true
  gather_facts: false

  tasks:
    - name: Create DRBD NFS mount directory
      file:
        path: /share/drbd_nfs
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Deploy NFS exports configuration
      copy:
        src: /root/exports
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'
