---
- name: Verify and create LVM for DRBD on both nodes
  hosts:
    - svc-1.kube.lan
    - svc-2.kube.lan
  become: yes
  gather_facts: false
  serial: 0   # ensure parallel execution

  vars:
    disk: /dev/nvme0n2
    vg_name: drbd_vg
    lv_name: drbd_lv
    lv_size: 5G
    monitor_script: monitor_script: "{{ ansible_env.HOME }}/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/scripts/DRBD+NFS/02-drbd-disk-moniter.py"

  ########################################################
  # PRE-CHECKS (NO CHANGES)
  ########################################################
  pre_tasks:

    - name: Verify disk exists
      stat:
        path: "{{ disk }}"
      register: disk_stat

    - name: Fail if disk does not exist
      fail:
        msg: "Disk {{ disk }} does not exist on {{ inventory_hostname }}"
      when: not disk_stat.stat.exists

    - name: Check if disk is already a PV
      command: pvs --noheadings {{ disk }}
      register: pv_check
      changed_when: false
      failed_when: false

    - name: Fail if disk is already a Physical Volume
      fail:
        msg: "Disk {{ disk }} is already a PV on {{ inventory_hostname }}"
      when: pv_check.stdout | trim != ""

    - name: Check if VG already exists
      command: vgs {{ vg_name }}
      register: vg_check
      changed_when: false
      failed_when: false

    - name: Fail if VG already exists
      fail:
        msg: "VG {{ vg_name }} already exists on {{ inventory_hostname }}"
      when: vg_check.rc == 0

    - name: Check if LV already exists
      command: lvs {{ vg_name }}/{{ lv_name }}
      register: lv_check
      changed_when: false
      failed_when: false

    - name: Fail if LV already exists
      fail:
        msg: "LV {{ lv_name }} already exists on {{ inventory_hostname }}"
      when: lv_check.rc == 0

    - name: Mark node as verified
      set_fact:
        node_verified: true

  ########################################################
  # GLOBAL VERIFICATION (ALL OR NOTHING)
  ########################################################
- name: Ensure verification passed on ALL nodes
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Abort if any node failed verification
      fail:
        msg: "Verification failed on one or more nodes. Aborting LVM creation on ALL nodes."
      when: >
        groups['all']
        | map('extract', hostvars, 'node_verified')
        | select('undefined')
        | list
        | length > 0

  ########################################################
  # APPLY CHANGES (SAFE TO RUN)
  ########################################################
- name: Create LVM on both nodes
  hosts:
    - svc-1.kube.lan
    - svc-2.kube.lan
  become: yes
  gather_facts: false

  tasks:

    - name: Ensure LVM tools are installed
      apt:
        name: lvm2
        state: present
        update_cache: yes

    - name: Create Physical Volume
      command: pvcreate {{ disk }}

    - name: Create Volume Group
      lvg:
        vg: "{{ vg_name }}"
        pvs: "{{ disk }}"
        state: present

    - name: Create Logical Volume
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ lv_name }}"
        size: "{{ lv_size }}"
        state: present

# ==================================================
# DRBD Disk Monitor Script
# ==================================================
- name: Verify DRBD disk monitor script exists
  stat:
    path: "{{ ansible_env.HOME }}/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/scripts/DRBD+NFS/02-drbd-disk-moniter.py"
  register: monitor_script_stat

- name: Fail if DRBD disk monitor script missing
  fail:
    msg: "DRBD disk monitor script not found in user HOME"
  when: not monitor_script_stat.stat.exists

- name: Ensure monitor script is executable
  file:
    path: "{{ ansible_env.HOME }}/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/scripts/DRBD+NFS/02-drbd-disk-moniter.py"
    mode: '0755'

- name: Run DRBD disk monitor script
  command: >
    python3 {{ ansible_env.HOME }}/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/scripts/DRBD+NFS/02-drbd-disk-moniter.py
  changed_when: false

