---
- name: DRBD Pre-checks on both nodes
  hosts: [svc-1.kube.lan, svc-2.kube.lan]
  become: true
  gather_facts: true
  serial: 0
  vars:
    vg_name: drbd_vg
    lv_name: drbd_lv
    backing_lv: "/dev/{{ vg_name }}/{{ lv_name }}"

  tasks:
    - name: Verify backing LV exists
      stat:
        path: "{{ backing_lv }}"
      register: lv_stat

    - name: Abort if backing LV missing
      fail:
        msg: "Backing LV {{ backing_lv }} missing on {{ inventory_hostname }}"
      when: not lv_stat.stat.exists

    - name: Mark node as verified
      set_fact:
        drbd_node_verified: true

- name: Ensure BOTH nodes passed pre-checks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Abort if any node failed verification
      fail:
        msg: "DRBD pre-check failed on one or both nodes. Aborting entire setup."
      when: >
        not hostvars['svc-1.kube.lan'].get('drbd_node_verified', false) or
        not hostvars['svc-2.kube.lan'].get('drbd_node_verified', false)

- name: Install and configure DRBD on both nodes
  hosts: [svc-1.kube.lan, svc-2.kube.lan]
  become: true
  gather_facts: false
  serial: 0
  vars:
    vg_name: drbd_vg
    lv_name: drbd_lv
    drbd_res: kube
    backing_lv: "/dev/{{ vg_name }}/{{ lv_name }}"

  tasks:
    - name: Install DRBD packages
      apt:
        name:
          - drbd-utils
          - nfs-common
          - nfs-kernel-server
          - rpcbind
        state: present
        update_cache: yes

    - name: Load DRBD kernel module
      modprobe:
        name: drbd
        state: present

    - name: Ensure DRBD loads at boot
      copy:
        dest: /etc/modules-load.d/drbd.conf
        content: "drbd\n"
        mode: '0644'

    - name: Install DRBD resource file
      copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/drbd-nfs/kube.res
        dest: /etc/drbd.d/kube.res
        owner: root
        group: root
        mode: '0644'

    - name: Validate DRBD configuration
      command: drbdadm dump {{ drbd_res }}
      changed_when: false

    - name: Ensure DRBD service is enabled and started (for boot persistence)
      systemd:
        name: drbd
        enabled: true
        state: started

- name: Initialize DRBD resources on both nodes
  hosts: [svc-1.kube.lan, svc-2.kube.lan]
  become: true
  gather_facts: false
  serial: 0
  vars:
    drbd_res: kube

  tasks:
    - name: Check DRBD status
      command: drbdadm status {{ drbd_res }}
      register: drbd_status
      failed_when: false
      changed_when: false

    - name: Create DRBD metadata (only if missing)
      command: drbdadm create-md --force {{ drbd_res }}
      when: drbd_status.rc != 0

    - name: Bring DRBD resource up (idempotent)
      command: drbdadm up {{ drbd_res }}
      register: drbd_up_result
      failed_when: 
        - drbd_up_result.rc != 0
        - "'is configured' not in drbd_up_result.stderr"
      changed_when: false

- name: Promote Primary and wait for sync
  hosts: svc-1.kube.lan
  become: true
  gather_facts: false
  vars:
    drbd_res: kube

  tasks:
    - name: Promote to Primary (idempotent)
      command: drbdadm primary --force {{ drbd_res }}
      register: promote_result
      failed_when: 
        - promote_result.rc != 0
        - "'already primary' not in promote_result.stderr"
      changed_when: false

    - name: Wait for DRBD sync to complete
      shell: |
        grep -q 'ds:UpToDate/UpToDate' /proc/drbd && \
        grep -q 'cs:Connected' /proc/drbd && \
        ! grep -q 'oos:[^0]' /proc/drbd
      register: drbd_sync_check
      retries: 99
      delay: 15
      until: drbd_sync_check.rc == 0
      changed_when: false
      failed_when: false
