---
# ==================================================
# PRIMARY NODE – svc-1
# ==================================================
- name: Configure DRBD-backed NFS server on svc-1 (Primary)
  hosts: svc-1.kube.lan
  become: true
  gather_facts: true

  tasks:
    # ==================================================
    # Verify DRBD device is ready and Primary
    # ==================================================
    - name: Check DRBD resource 'kube' status
      command: drbdadm status kube
      register: drbd_status
      changed_when: false
      failed_when: false

    - name: Fail if DRBD status command failed
      fail:
        msg: "DRBD status check failed: {{ drbd_status.stderr | default(drbd_status.stdout) }}"
      when: drbd_status.rc != 0

    - name: Fail if DRBD not Primary or replication not Established
      fail:
        msg: |
          DRBD must be Primary with Established replication.
          Current status:
          {{ drbd_status.stdout | indent(10) }}
      when: >
        (drbd_status.stdout is not search('^kube role:Primary', multiline=True)) or
        ('replication:Established' not in drbd_status.stdout)

    # ==================================================
    # Device existence check
    # ==================================================
    - name: Verify DRBD device exists
      stat:
        path: /dev/drbd0
      register: drbd_device

    - name: Fail if DRBD device missing
      fail:
        msg: "/dev/drbd0 does not exist. Is DRBD resource 'kube' attached?"
      when: not drbd_device.stat.exists

    # ==================================================
    # Mount status check (rerun safety)
    # ==================================================
    - name: Check if DRBD device is already mounted
      command: mountpoint -q /share/drbd_nfs
      register: mount_check
      failed_when: false
      changed_when: false

    # ==================================================
    # Filesystem check
    # ==================================================
    - name: Check filesystem type on /dev/drbd0
      command: file -sL /dev/drbd0
      register: fs_check
      changed_when: false
      failed_when: false
      args:
        warn: false

    - name: Create XFS filesystem on /dev/drbd0 (only if unformatted)
      filesystem:
        fstype: xfs
        dev: /dev/drbd0
      when:
        - mount_check.rc != 0
        - "'XFS filesystem' not in (fs_check.stdout | default(''))"

    # ==================================================
    # Mount DRBD volume (persistent & rerun-safe)
    # ==================================================
    - name: Ensure mount point exists
      file:
        path: /share/drbd_nfs
        state: directory
        mode: '0755'

    - name: Mount /dev/drbd0 to /share/drbd_nfs
      mount:
        path: /share/drbd_nfs
        src: /dev/drbd0
        fstype: xfs
        opts: defaults
        state: ephemeral

    # ==================================================
    # Kubernetes directory structure
    # ==================================================
    - name: Create Kubernetes StorageClass directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "1000"
        group: "1000"
        mode: '0777'
      loop:
        - /share/drbd_nfs/kubernetes/StorageClass/Delete
        - /share/drbd_nfs/kubernetes/StorageClass/Retain

    # ==================================================
    # NFS Exports
    # ==================================================
    - name: Copy exports file
      copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/nfs/exports
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'

    - name: Reload NFS exports
      command: exportfs -rav
      register: export_result
      changed_when: "'exporting' in export_result.stdout"

    # ==================================================
    # NFS Service
    # ==================================================
    - name: Enable and start NFS server
      systemd:
        name: nfs-server
        enabled: true
        state: started


# ==================================================
# SECONDARY NODE – svc-2
# ==================================================
- name: Configure DRBD NFS standby on svc-2
  hosts: svc-2.kube.lan
  become: true
  gather_facts: false

  tasks:
    # ==================================================
    # Safety guard – must NOT be Primary (local role only)
    # ==================================================
    - name: Check DRBD resource 'kube' status
      command: drbdadm status kube
      register: drbd_status
      changed_when: false
      failed_when: false

    - name: Fail if svc-2 local DRBD role is Primary
      fail:
        msg: "svc-2 is Primary — aborting to avoid split-brain risk"
      when: drbd_status.stdout is search('^kube role:Primary', multiline=True)

    # ==================================================
    # Post-sync tasks (NO LOGIC CHANGED)
    # ==================================================
    - name: Create DRBD NFS mount directory
      file:
        path: /share/drbd_nfs
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Deploy NFS exports configuration
      copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-02/config_Files/nfs/exports
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'
