---
- name: Clone Kubernetes Cluster Config Repository
  hosts: kube-cp-1.kube.lan
  become: true
  gather_facts: true

  vars:
    repo_url: "https://github.com/shahrukh244/kubernetes_Cluster_Config.git"
    dest_dir: "/root/kubernetes_Cluster_Config"

  tasks:

    - name: Ensure git is installed
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone kubernetes_Cluster_Config repo
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        version: "HEAD"
        force: yes
        update: yes
        accept_hostkey: yes
