---
- name: Configure DRBD-backed NFS server on svc-1 (Primary)
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    # ==================================================
    # Verify DRBD device is ready and Primary
    # ==================================================
    - name: Check DRBD resource 'kube' status
      command: drbdadm status kube
      register: drbd_status
      changed_when: false
      failed_when: false

    - name: Fail if DRBD status command failed
      fail:
        msg: "DRBD status check failed: {{ drbd_status.stderr | default(drbd_status.stdout) }}"
      when: drbd_status.rc != 0

    - name: Fail if DRBD not Primary or replication not Established
      fail:
        msg: |
          DRBD must be Primary with Established replication.
          Current status:
          {{ drbd_status.stdout | indent(10) }}
      when: >
        ('role:Primary' not in drbd_status.stdout) or
        ('replication:Established' not in drbd_status.stdout)

    # ==================================================
    # Device existence check (critical fix)
    # ==================================================
    - name: Verify DRBD device exists
      stat:
        path: /dev/drbd0
      register: drbd_device
      failed_when: false

    - name: Fail if DRBD device missing
      fail:
        msg: "/dev/drbd0 does not exist. Is DRBD resource 'kube' properly configured and attached?"
      when: not drbd_device.stat.exists

    # ==================================================
    # Filesystem & Mount (fixed condition)
    # ==================================================
    - name: Check filesystem type on /dev/drbd0
      command: file -sL /dev/drbd0
      register: fs_check
      changed_when: false
      failed_when: false
      args:
        warn: false
      when: drbd_device.stat.exists

    - name: Create XFS filesystem on /dev/drbd0 (only if unformatted)
      filesystem:
        fstype: xfs
        dev: /dev/drbd0
      when: 
        - drbd_device.stat.exists
        - "'XFS filesystem' not in (fs_check.stdout | default(''))"

    - name: Ensure mount point exists
      file:
        path: /share/drbd_nfs
        state: directory
        mode: '0755'

    - name: Mount /dev/drbd0 to /share/drbd_nfs
      mount:
        path: /share/drbd_nfs
        src: /dev/drbd0
        fstype: xfs
        opts: defaults
        state: mounted

    # ==================================================
    # Kubernetes directory structure
    # ==================================================
    - name: Create Kubernetes StorageClass directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "1000"
        group: "1000"
        mode: '0777'
      loop:
        - /share/drbd_nfs/kubernetes/StorageClass/Delete
        - /share/drbd_nfs/kubernetes/StorageClass/Retain

    # ==================================================
    # NFS Exports
    # ==================================================
    - name: Copy exports file
      copy:
        src: /root/exports
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'

    - name: Reload NFS exports
      command: exportfs -rav
      register: export_result
      changed_when: "'exporting' in export_result.stdout"

    # ==================================================
    # NFS Service
    # ==================================================
    - name: Enable and start NFS server
      systemd:
        name: nfs-server
        enabled: true
        state: started
