---
- name: Join kube-cp-3 to Kubernetes cluster as control-plane node
  hosts: kube-cp-3.kube.lan
  become: yes
  gather_facts: true

  vars:
    primary_master: "kube-cp-1.kube.lan"

  tasks:
    # ==================================================
    # FETCH JOIN COMMAND
    # ==================================================
    - name: Fetch control-plane join command from {{ primary_master }}
      delegate_to: "{{ primary_master }}"
      delegate_facts: false
      vars:
        ansible_user: root
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      shell: |
        LB=$(kubectl -n kube-system get cm kubeadm-config -o jsonpath='{.data.ClusterConfiguration}' \
          | grep 'controlPlaneEndpoint' | awk -F': ' '{print $2}' | tr -d '\r\n "')
        TOKEN=$(kubeadm token create)
        CERT_KEY=$(kubeadm init phase upload-certs --upload-certs 2>/dev/null \
          | grep -A1 'Using certificate key:' | tail -n1 | tr -d ' ')
        CA_HASH=$(openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt \
          | openssl rsa -pubin -outform der 2>/dev/null \
          | openssl dgst -sha256 -hex | sed 's/^.* //')
        echo "kubeadm join ${LB} --token ${TOKEN} \
          --discovery-token-ca-cert-hash sha256:${CA_HASH} \
          --control-plane --certificate-key ${CERT_KEY}"
      register: join_cmd
      changed_when: false

    # ==================================================
    # CLEAN PREVIOUS STATE
    # ==================================================
    - name: Ensure /etc/kubernetes is clean before joining
      file:
        path: /etc/kubernetes
        state: absent

    # ==================================================
    # JOIN CONTROL PLANE
    # ==================================================
    - name: Join the cluster as control-plane
      command: "{{ join_cmd.stdout }}"
      register: join_result
      changed_when: "'preflight' in join_result.stdout"

    # ==================================================
    # WAIT FOR NODE
    # ==================================================
    - name: Wait for node to register
      command: kubectl --kubeconfig /etc/kubernetes/admin.conf get node kube-cp-3.kube.lan --no-headers
      register: node_check
      until: node_check.rc == 0
      retries: 10
      delay: 6
      changed_when: false

    # ==================================================
    # KUBECONFIG SETUP
    # ==================================================
    - name: Create .kube directory
      file:
        path: /root/.kube
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Copy admin.conf to kubeconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root
        group: root
        mode: "0600"

    - name: Export KUBECONFIG globally
      copy:
        dest: /etc/profile.d/kubeconfig.sh
        content: |
          export KUBECONFIG=/etc/kubernetes/admin.conf
        mode: "0644"

    # ==================================================
    # INSTALL ETCD CLIENT
    # ==================================================
    - name: Install etcd-client
      apt:
        name: etcd-client
        state: present
        update_cache: yes

    # ==================================================
    # ETCD HEALTH CHECK
    # ==================================================
    - name: Check etcd endpoint health
      command: >
        etcdctl
        --endpoints=https://127.0.0.1:2379
        --cacert=/etc/kubernetes/pki/etcd/ca.crt
        --cert=/etc/kubernetes/pki/etcd/peer.crt
        --key=/etc/kubernetes/pki/etcd/peer.key
        endpoint health
      environment:
        ETCDCTL_API: "3"
      register: etcd_health
      changed_when: false
      failed_when: "'unhealthy' in etcd_health.stdout"

    - name: Show etcd endpoint health
      debug:
        var: etcd_health.stdout

    # ==================================================
    # ETCD MEMBER LIST
    # ==================================================
    - name: List etcd members
      command: >
        etcdctl
        --endpoints=https://127.0.0.1:2379
        --cacert=/etc/kubernetes/pki/etcd/ca.crt
        --cert=/etc/kubernetes/pki/etcd/peer.crt
        --key=/etc/kubernetes/pki/etcd/peer.key
        member list
      environment:
        ETCDCTL_API: "3"
      register: etcd_members
      changed_when: false

    - name: Show etcd members
      debug:
        var: etcd_members.stdout

    # ==================================================
    # SUCCESS
    # ==================================================
    - name: Success
      debug:
        msg: "✅ kube-cp-3.kube.lan joined the control plane successfully and etcd is healthy!"
