---
- name: Full Ubuntu system setup with services
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    # -------- SWAP (smart & idempotent) --------

    - name: Check runtime swap status
      ansible.builtin.command: swapon --noheadings
      register: swap_runtime
      changed_when: false
      failed_when: false

    - name: Disable swap if enabled
      ansible.builtin.command: swapoff -a
      when: swap_runtime.stdout | trim != ""
      register: swapoff_result

    - name: Detect active swap entries in fstab
      ansible.builtin.shell: |
        awk '!/^[[:space:]]*#/ && $0 ~ /swap/ { print }' /etc/fstab
      register: swap_fstab_active
      changed_when: false

    - name: Comment all active swap entries in fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^[^#].*swap'
        line: '#\g<0>'
        backrefs: yes
      when: swap_fstab_active.stdout | trim != ""
      register: fstab_comment_result

    - name: Final swap verification
      ansible.builtin.command: swapon --show
      register: final_swap_check
      changed_when: false

    # -------- Feedback Messages --------
    - name: Report swap status
      ansible.builtin.debug:
        msg: |
          {% if swap_runtime.stdout | trim == "" %}
          [OK] No active swap found at runtime — nothing to disable.
          {% else %}
          [OK] Runtime swap has been disabled.
          {% endif %}
      when: swap_runtime.stdout is defined

    - name: Report fstab swap handling
      ansible.builtin.debug:
        msg: |
          {% if swap_fstab_active.stdout | trim == "" %}
          [OK] No active swap entries in /etc/fstab — already commented or absent.
          {% else %}
          [OK] Active swap entries in /etc/fstab have been commented out.
          {% endif %}
      when: swap_fstab_active.stdout is defined

    - name: Show final swap state (for visibility)
      ansible.builtin.debug:
        msg: "[OK] Final swap state: {{ final_swap_check.stdout | default('none') | trim or 'none' }}"
