---
- name: Full Ubuntu system setup with services
  hosts: bastion.kube.lan
  become: true
  gather_facts: true

  tasks:
    # -------- UFW (smart & idempotent) --------

    - name: Check if UFW service exists
      ansible.builtin.stat:
        path: /lib/systemd/system/ufw.service
      register: ufw_service
      changed_when: false

    - name: Stop and disable UFW if present
      ansible.builtin.service:
        name: ufw
        state: stopped
        enabled: false
      when: ufw_service.stat.exists
      register: ufw_disable_result

    # -------- Feedback Messages --------
    - name: Report UFW status
      ansible.builtin.debug:
        msg: |
          {% if not ufw_service.stat.exists %}
          [OK] UFW is not installed — nothing to do.
          {% elif ufw_disable_result.changed %}
          [OK] UFW has been stopped and disabled.
          {% else %}
          [OK] UFW is already stopped and disabled.
          {% endif %}
