---
- name: Install OpenShift 'oc' CLI client (v4.14.9)
  hosts: localhost
  become: true
  vars:
    oc_url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.14.9/openshift-client-linux.tar.gz"
    oc_dest: /usr/local/bin/oc
    tmp_dir: /tmp/oc_install_{{ ansible_date_time.epoch }}

  tasks:
    - name: Check if 'oc' is already installed
      stat:
        path: "{{ oc_dest }}"
      register: oc_stat

    - name: Skip installation if 'oc' already exists
      debug:
        msg: "'oc' already installed at {{ oc_dest }}. Skipping download and extraction."
      when: oc_stat.stat.exists

    - name: Create temporary directory for download
      file:
        path: "{{ tmp_dir }}"
        state: directory
        mode: '0755'
      when: not oc_stat.stat.exists

    - name: Download OpenShift client tarball
      get_url:
        url: "{{ oc_url }}"
        dest: "{{ tmp_dir }}/openshift-client-linux.tar.gz"
        mode: '0644'
      when: not oc_stat.stat.exists

    - name: Extract tarball
      unarchive:
        src: "{{ tmp_dir }}/openshift-client-linux.tar.gz"
        dest: "{{ tmp_dir }}"
        remote_src: yes
      when: not oc_stat.stat.exists

    - name: Locate 'oc' binary in extracted content
      find:
        paths: "{{ tmp_dir }}"
        patterns: "oc"
        file_type: file
      register: found_oc
      when: not oc_stat.stat.exists

    - name: Fail if 'oc' binary not found in archive
      assert:
        that: found_oc.files | length > 0
        fail_msg: "Could not find 'oc' binary in extracted archive. Download may be corrupt or structure changed."
      when: not oc_stat.stat.exists

    - name: Copy 'oc' to system path
      copy:
        src: "{{ found_oc.files[0].path }}"
        dest: "{{ oc_dest }}"
        remote_src: yes
        mode: '0755'
      when: not oc_stat.stat.exists

    - name: Clean up temporary directory
      file:
        path: "{{ tmp_dir }}"
        state: absent
      when: not oc_stat.stat.exists

    - name: Verify 'oc' installation and show version
      command: "{{ oc_dest }} version --client"
      register: oc_version
      changed_when: false
      when: oc_stat.stat.exists or (found_oc.files | length > 0)

    - name: Report final status
      debug:
        msg: >
          OpenShift 'oc' CLI is installed at {{ oc_dest }}.
          Version: {{ (oc_version.stdout_lines | first) if (oc_version.stdout_lines | length > 0) else 'unknown' }}
