---
- name: Hostname Setup
  hosts: svc-2.kube.lan
  become: true
  gather_facts: true

  tasks:

    # -------- Set hostname --------
    - name: Set system hostname to svc-2.kube.lan
      ansible.builtin.hostname:
        name: svc-2.kube.lan

    - name: Show hostname change
      ansible.builtin.debug:
        msg: "[+] Hostname set to svc-2.kube.lan"
