---
- name: Root Password Setup
  hosts: localhost
  become: true
  gather_facts: true

  tasks:

    # -------- Root password (only if different) --------
    - name: Check current root password hash
      ansible.builtin.command: getent shadow root
      register: root_shadow
      changed_when: false

    - name: Set root password if different
      ansible.builtin.user:
        name: root
        password: "{{ '123' | password_hash('sha512') }}"
      when: "'{{ '123' | password_hash('sha512') }}' not in root_shadow.stdout"
      notify: Restart SSH

  handlers:

    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
        enabled: true
