---
- name:  DHCP Server Setup
  hosts: localhost
  become: true
  gather_facts: false

  tasks:
    - name: Install ISC DHCP Server (only if missing)
      ansible.builtin.apt:
        name: isc-dhcp-server
        state: present
        update_cache: yes

    - name: Set DHCP interface to ens33 in /etc/default/isc-dhcp-server
      ansible.builtin.lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: '^INTERFACESv4='
        line: 'INTERFACESv4="ens33"'
        backup: yes

    - name: Copy dhcpd.conf
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-02/config_Files/dhcp/dhcpd.conf
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Touch and set permissions on check_dhcp.log
      ansible.builtin.file:
        path: /var/log/check_dhcp.log
        state: touch
        mode: '0644'

    - name: Validate DHCP configuration
      ansible.builtin.command:
        cmd: dhcpd -t -cf /etc/dhcp/dhcpd.conf
      changed_when: false

    - name: Enable and restart DHCP server
      ansible.builtin.service:
        name: isc-dhcp-server
        state: restarted
        enabled: true
