---
- name: Full Ubuntu system setup with Keepalived
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
        # -------- BIND --------
    - name: Install BIND9
      ansible.builtin.apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Ensure BIND zones directory exists
      ansible.builtin.file:
        path: /etc/bind/zones
        state: directory
        mode: 0755

    - name: Copy named.conf.options
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-02/config_Files/dns/named.conf.options
        dest: /etc/bind/named.conf.options
        backup: yes

    - name: Copy named.conf.local
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-02/config_Files/dns/named.conf.local
        dest: /etc/bind/named.conf.local
        backup: yes

    - name: Restart BIND9
      ansible.builtin.service:
        name: bind9
        state: restarted
        enabled: true
