---
- name: Reboot System in 15sec
  hosts: svc-2.kube.lan
  become: true
  gather_facts: true

  tasks:

    - name: Countdown before reboot
      ansible.builtin.shell: |
        echo "========== Countdown before reboot =========="
        for i in $(seq 15 -1 1); do
          echo "⏳ Rebooting in $i seconds..."
          sleep 1
        done
      args:
        executable: /bin/bash

    - name: Reboot the system
      ansible.builtin.command: shutdown -r now
      async: 1
      poll: 0
