---
- name: NFS Server Setup (Safe, Verified)
  hosts: localhost
  become: true
  gather_facts: true

  tasks:

    # -------- NFS (Safe, Verified) --------

    - name: Check if NFS server is installed
      ansible.builtin.command: exportfs -v
      register: nfs_check
      failed_when: false
      changed_when: false

    - name: Install NFS server (only if missing)
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
        update_cache: yes
      when: nfs_check.rc != 0

    - name: Ensure NFS export directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: 1000
        group: 1000
        mode: "0777"
      loop:
        - /shares/kubernetes/StorageClass/Delete
        - /shares/kubernetes/StorageClass/Retain

    - name: Copy /etc/exports from file
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/nfs/exports
        dest: /etc/exports
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Validate NFS exports
      ansible.builtin.command: exportfs -rav
      register: exportfs_validate
      changed_when: false

    - name: Enable and restart NFS server (only if exports valid)
      ansible.builtin.service:
        name: nfs-kernel-server
        state: restarted
        enabled: true
      when: exportfs_validate.rc == 0

