---
- name: Full Ubuntu system setup with services
  hosts: localhost
  become: true

  tasks:

    # -------- SSH (smart & idempotent) --------

    - name: Read sshd_config
      ansible.builtin.slurp:
        path: /etc/ssh/sshd_config
      register: sshd_config_raw
      changed_when: false

    - name: Decode sshd_config
      ansible.builtin.set_fact:
        sshd_config: "{{ sshd_config_raw.content | b64decode }}"
      changed_when: false

    # ---- PermitRootLogin ----
    - name: Ensure PermitRootLogin yes
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#\s]*PermitRootLogin\s+'
        line: 'PermitRootLogin yes'
      when: "'PermitRootLogin yes' not in sshd_config"
      notify: Restart SSH

    # ---- PasswordAuthentication ----
    - name: Ensure PasswordAuthentication yes
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#\s]*PasswordAuthentication\s+'
        line: 'PasswordAuthentication yes'
      when: "'PasswordAuthentication yes' not in sshd_config"
      notify: Restart SSH

    # ---- UsePAM ----
    - name: Ensure UsePAM yes
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#\s]*UsePAM\s+'
        line: 'UsePAM yes'
      when: "'UsePAM yes' not in sshd_config"
      notify: Restart SSH

    # ---- Root password (only if different) ----
    - name: Check current root password hash
      ansible.builtin.command: getent shadow root
      register: root_shadow
      changed_when: false

    - name: Set root password if different
      ansible.builtin.user:
        name: root
        password: "{{ '123' | password_hash('sha512') }}"
      when: "'{{ '123' | password_hash('sha512') }}' not in root_shadow.stdout"

  handlers:

    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
        enabled: true
