---
- name: IP Forwarding & NAT Setup
  hosts: localhost
  become: true
  gather_facts: false

  tasks:

    # -------- Enable IP Forwarding --------
    - name: Enable IPv4 forwarding (runtime + persistent)
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

    # -------- NAT & FORWARD Rules --------
    - name: NAT POSTROUTING (MASQUERADE for LAN → WAN)
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        source: 10.0.0.0/24
        out_interface: ens32
        jump: MASQUERADE

    - name: Allow LAN (ens33) → WAN (ens32) forwarding
      ansible.builtin.iptables:
        chain: FORWARD
        in_interface: ens33
        out_interface: ens32
        jump: ACCEPT

    - name: Allow established WAN (ens32) → LAN (ens33) traffic
      ansible.builtin.iptables:
        chain: FORWARD
        in_interface: ens32
        out_interface: ens33
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT

    # -------- Persist Rules --------
    - name: Install iptables-persistent (only if missing)
      ansible.builtin.apt:
        name: iptables-persistent
        state: present
        update_cache: yes

    - name: Save iptables rules persistently
      ansible.builtin.command:
        cmd: netfilter-persistent save
      changed_when: false
