---
- name: Full Ubuntu system setup with services
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    # -------- SSH KEYGEN (smart & idempotent) --------

    - name: Check if root SSH private key exists
      ansible.builtin.stat:
        path: /root/.ssh/id_ed25519
      register: root_ssh_key

    - name: Ensure /root/.ssh directory exists
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Generate ed25519 SSH key for root (no passphrase)
      ansible.builtin.command: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ""
      when: not root_ssh_key.stat.exists

    - name: Ensure private key permissions are correct
      ansible.builtin.file:
        path: /root/.ssh/id_ed25519
        owner: root
        group: root
        mode: "0600"
      when: root_ssh_key.stat.exists

    - name: Ensure public key permissions are correct
      ansible.builtin.file:
        path: /root/.ssh/id_ed25519.pub
        owner: root
        group: root
        mode: "0644"
      when: root_ssh_key.stat.exists


