---
- name: Chrony & Timezone Setup (Safe, Verified)
  hosts: localhost
  become: true
  gather_facts: true

  tasks:

    # -------- Timezone (Safe) --------

    - name: Check current timezone
      ansible.builtin.command: timedatectl show -p Timezone --value
      register: current_timezone
      changed_when: false

    - name: Set timezone to Asia/Kolkata (only if needed)
      ansible.builtin.command: timedatectl set-timezone Asia/Kolkata
      when: current_timezone.stdout != "Asia/Kolkata"

    # -------- Chrony (Safe, Verified) --------

    - name: Check if chrony is installed
      ansible.builtin.command: chronyc tracking
      register: chrony_check
      failed_when: false
      changed_when: false

    - name: Install chrony (only if missing)
      ansible.builtin.apt:
        name: chrony
        state: present
        update_cache: yes
      when: chrony_check.rc != 0

    - name: Ensure chrony config directory exists
      ansible.builtin.file:
        path: /etc/chrony
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy chrony.conf
      ansible.builtin.copy:
        src: /root/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/config_Files/chrony/chrony.conf
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Validate chrony configuration
      ansible.builtin.command: chronyd -Q -f /etc/chrony/chrony.conf
      register: chrony_validate
      changed_when: false

    - name: Enable and restart chrony (only if config valid)
      ansible.builtin.service:
        name: chrony
        state: restarted
        enabled: true
      when: chrony_validate.rc == 0
