- name: Run all service node setup scripts and playbooks with delays
  hosts: localhost
  gather_facts: false
  vars:
    base_dir: "{{ lookup('env', 'HOME') }}/kubernetes_Cluster_Config/service_Node_Config/service_Node-01/scripts"

  tasks:

      - name: Include 00 - sshEnableLogin.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/00 - sshEnableLogin.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5
  
    - name: Run 01 - InstallAnsible.py
      ansible.builtin.command: python3 "{{ base_dir }}/01 - InstallAnsible.py"
      args:
        chdir: "{{ base_dir }}"
      changed_when: true

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 02 - hostnameSet.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/02 - hostnameSet.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 03 - setIP.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/03 - setIP.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 04 - NAT.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/04 - NAT.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 05 - rootLoginEnable.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/05 - rootLoginEnable.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 06 - rootPasswdChange.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/06 - rootPasswdChange.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 07 - sshKeyGen.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/07 - sshKeyGen.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 08 - disableSwap.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/08 - disableSwap.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 09 - disableUFW.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/09 - disableUFW.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 10 - keepalived.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/10 - keepalived.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 11 - dhcp.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/11 - dhcp.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 12 - bind9.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/12 - bind9.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 13 - ntp.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/13 - ntp.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 14 - haproxy.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/14 - haproxy.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 15 - drbd.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/15 - drbd.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Run 15.1 - drbd-disk-moniter.py
      ansible.builtin.command: python3 "{{ base_dir }}/15.1 - drbd-disk-moniter.py"
      args:
        chdir: "{{ base_dir }}"
      changed_when: true

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 15.2 - drbd-exports.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/15.2 - drbd-exports.yaml"

    - name: Wait 5 seconds before next step
      ansible.builtin.pause:
        seconds: 5

    - name: Include 16 - reboot.yaml
      ansible.builtin.include_playbook: "{{ base_dir }}/16 - reboot.yaml"
